sudo: required
dist: trusty
language: c
addons:
  apt:
    packages:
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
compiler:
 - clang
 - gcc
before_script:
 - ./autogen.sh
script: make
